# Generated by Django 5.2.4 on 2025-07-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('batch', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('guardian', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('other', 'Other')], max_length=6)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
